apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  labels:
    app: cloud-native
  name: cloud-native
  namespace: nju25
spec:
  replicas: 1  #运行容器的副本数
  selector:
    matchLabels:
      app: cloud-native
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: cloud-native
    spec:
      containers: #docker容器的配置
        - image: harbor.edu.cn/nju25/cloud-native:{VERSION} #pull镜像的地址
          name: cloud-native
      imagePullSecrets:
        - name: nju25
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-native
  namespace: nju25
  labels:
    app: cloud-native
spec:
  type: NodePort
  selector:
    app: cloud-native
  ports:
    - name: tcp
      nodePort: 31105  #host's port
      protocol: TCP
      port: 8080  #service's port
      targetPort: 8080  #target pod's port
